### ISSUE TITLE
Please update README.md

### ISSUE THREAD

**Issue by budumlu** [mttaggart/gitclass#2]
Hello Mr. Taggart,

I've installed your little tool on a raspberry pi succesfully :-)

But now I'm a little bit stucked. Would you mind update your README.md, so that I can firgure out more easily, how this tool can help me in my classroom?

Some issues that I found:

1. replace "gitclass add-student" by "gitclass add"
2. "gitclass init name-of-class" does not create a folder, only a json-file
3. "gitclass -V" and "gitclass -h" show a wrong version-number
4. Would you mind add some simple git-steps I have to perform to get my git-master- and git-student-repos up and running?

Thanks a lot in advance!

**Comment by mttaggart** [comment]
Hoping that 21a211020c9e7cf23e97704f1895caef448059dc solves the `README` issues that you identified. The latest release should fix the `init` issue. As for your number 4. I'll do that here.

The basic concept here is to have your students clone your master repository. Then, as they commit/push code, you update your local copy of their repos using `gitclass`. Here's an example:

Let's say I have a repository of code, with each folder representing a different exercise. [Something like this](https://github.com/mirman-school/dcb). At the beginning of the year, students fork this repo and now have their own version of it. It is in this personal repo that they finish the exercises.

I as the teacher now have a logistical problem: I can either go and review each students' repo on GitHub, or use the already-powerful Git command line tools to inspect them. I like that approach. So I use `gitclass init` to set up my class and then `gitclass add` to add students to my class. As I expect code to come in, I run `gitclass update` to pull their latest code.

I hope this helps.
